name: Sync Repository

on:
  schedule:
    - cron: '0 * * * *' # 每小时运行一次，可以根据需求自行调整

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Sync repository
      run: |
        git config --global user.name "Your Name"
        git config --global user.email "your-email@example.com"
        git remote add upstream https://github.com/other-user/repository.git
        git fetch upstream
        git checkout master
        git merge upstream/master --no-edit
        git push origin master
